-- PASSENGERS
CREATE TABLE passengers (
    passenger_id NUMBER PRIMARY KEY,
    name VARCHAR2(50),
    age NUMBER,
    gender VARCHAR2(10),
    phone VARCHAR2(15)
);

-- FLIGHTS
CREATE TABLE flights (
    flight_id NUMBER PRIMARY KEY,
    airline VARCHAR2(50),
    source VARCHAR2(50),
    destination VARCHAR2(50),
    departure_time DATE,
    arrival_time DATE,
    total_seats NUMBER
);

-- BOOKINGS
CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id NUMBER NOT NULL,
    flight_id NUMBER NOT NULL,
    seat_number NUMBER NOT NULL,
    booking_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'CONFIRMED',

    CONSTRAINT fk_passenger FOREIGN KEY (passenger_id)
        REFERENCES passengers(passenger_id),

    CONSTRAINT fk_flight FOREIGN KEY (flight_id)
        REFERENCES flights(flight_id),

    CONSTRAINT unique_seat_per_flight
        UNIQUE (flight_id, seat_number)
);

-- PAYMENTS
CREATE TABLE payments (
    payment_id NUMBER PRIMARY KEY,
    booking_id NUMBER,
    amount NUMBER,
    payment_method VARCHAR2(20),
    payment_date DATE,

    FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id)
);